/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationAuthorizationResourceDetailComponent: typeof import('./src/components/applications/details/authorizations/resources/ApplicationAuthorizationResourceDetailComponent.vue')['default']
    ApplicationAuthorizationResourceListComponent: typeof import('./src/components/applications/details/authorizations/resources/ApplicationAuthorizationResourceListComponent.vue')['default']
    ApplicationCredentialComponent: typeof import('./src/components/applications/details/ApplicationCredentialComponent.vue')['default']
    ApplicationDetailComponent: typeof import('./src/components/applications/ApplicationDetailComponent.vue')['default']
    ApplicationListComponent: typeof import('./src/components/applications/ApplicationListComponent.vue')['default']
    ApplicationSessionComponent: typeof import('./src/components/applications/details/ApplicationSessionComponent.vue')['default']
    ApplicationSettingComponent: typeof import('./src/components/applications/details/ApplicationSettingComponent.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    TagStatus: typeof import('./src/components/commons/TagStatus.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
